
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tofuto
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        deusaLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        signoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        signoTextField = new javax.swing.JTextField();
        deusaTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        topPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        voltarPanel = new javax.swing.JPanel();
        voltarLabel = new javax.swing.JLabel();
        cadastrarBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deusaLabel.setText("Deusa");
        background.add(deusaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        senhaLabel.setText("Senha");
        background.add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        signoLabel.setText("Signo");
        background.add(signoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        nomeLabel.setText("Nome");
        background.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        signoTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        background.add(signoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 140, 25));

        deusaTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        background.add(deusaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 140, 25));

        senhaTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        background.add(senhaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 25));

        nomeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        background.add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 140, 25));

        topPanel.setBackground(new java.awt.Color(0, 153, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        topPanel.add(closeLabel, java.awt.BorderLayout.LINE_END);

        voltarPanel.setBackground(new java.awt.Color(204, 204, 255));
        voltarPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        voltarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarLabel.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 24)); // NOI18N
        voltarLabel.setText(" Voltar");
        voltarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarLabelMouseExited(evt);
            }
        });
        voltarPanel.add(voltarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        topPanel.add(voltarPanel, java.awt.BorderLayout.LINE_START);

        background.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        cadastrarBut.setBackground(new java.awt.Color(102, 255, 204));
        cadastrarBut.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 18)); // NOI18N
        cadastrarBut.setText("CADASTRAR");
        cadastrarBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarButMouseExited(evt);
            }
        });
        cadastrarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButActionPerformed(evt);
            }
        });
        background.add(cadastrarBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 120, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseEntered
        voltarPanel.setBackground(Color.red);
    }//GEN-LAST:event_voltarLabelMouseEntered

    private void voltarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseExited
        Color cor = new Color(204,204,255);
        voltarPanel.setBackground(cor);
    }//GEN-LAST:event_voltarLabelMouseExited

    private void voltarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void cadastrarButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseExited
        Color joel = new Color(102,255,204);
        cadastrarBut.setBackground(joel);
    }//GEN-LAST:event_cadastrarButMouseExited

    private void cadastrarButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseEntered
        cadastrarBut.setBackground(Color.red);
    }//GEN-LAST:event_cadastrarButMouseEntered

    private void cadastrarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButActionPerformed
        cadastrar();
    }//GEN-LAST:event_cadastrarButActionPerformed
    private void cadastrar(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pstCheckDuplicateQuery = c.prepareStatement("select * from cachorro_clientes where nome = ?");
            pstCheckDuplicateQuery.setString(1, nomeTextField.getText());
            ResultSet rs = pstCheckDuplicateQuery.executeQuery();
            if(!rs.next()){
            PreparedStatement pst = c.prepareStatement("insert into cachorro_clientes(nome, senha, signo, deusa, admin) values (?,?,?,?,0)");
             pst.setString(1, nomeTextField.getText());
             pst.setString(2, senhaTextField.getText());
             pst.setString(3, signoTextField.getText());
             pst.setString(4, deusaTextField.getText());
             pst.execute();
             JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                 if(nomeTextField.getText().equals("Beatriz")){
                     JOptionPane.showMessageDialog(null, "Beatriz é o nome da Deusa da Beleza!! Belo nome para cadastro");
                 }Login l = new Login();
            l.setVisible(true);
            this.dispose();}else{
                JOptionPane.showMessageDialog(null, "Nome ja cadastrado escolha outro!!!");
                cadastrar();
            }
 
        }catch(Exception e){
        e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cadastrarBut;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel deusaLabel;
    private javax.swing.JTextField deusaTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JLabel signoLabel;
    private javax.swing.JTextField signoTextField;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel voltarLabel;
    private javax.swing.JPanel voltarPanel;
    // End of variables declaration//GEN-END:variables
}
