
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tofuto
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        nomeTextField1 = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        senhaTextField1 = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        entrarBut = new javax.swing.JButton();
        cadastrarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextField1ActionPerformed(evt);
            }
        });
        background.add(nomeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 30));

        nomeLabel.setText("Nome(User)");
        background.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
        background.add(senhaTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, 30));

        senhaLabel.setText("Senha");
        background.add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        topPanel.setBackground(new java.awt.Color(0, 153, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        topPanel.add(closeLabel, java.awt.BorderLayout.LINE_END);

        background.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        entrarBut.setBackground(java.awt.Color.red);
        entrarBut.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 18)); // NOI18N
        entrarBut.setText("ENTRAR");
        entrarBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarButMouseExited(evt);
            }
        });
        entrarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButActionPerformed(evt);
            }
        });
        background.add(entrarBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, 50));

        cadastrarButton1.setBackground(java.awt.Color.red);
        cadastrarButton1.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 18)); // NOI18N
        cadastrarButton1.setText("CADASTRAR");
        cadastrarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarButton1MouseExited(evt);
            }
        });
        cadastrarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButton1ActionPerformed(evt);
            }
        });
        background.add(cadastrarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 120, 50));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextField1ActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void entrarButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButMouseClicked
        if(nomeSenhaNotBlank()){
            checarLogin();
        }
        
    }//GEN-LAST:event_entrarButMouseClicked

    private void entrarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButActionPerformed
        
    }//GEN-LAST:event_entrarButActionPerformed

    private void cadastrarButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarButton1MouseClicked

    private void cadastrarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButton1ActionPerformed
        Cadastro cad = new Cadastro();
        cad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarButton1ActionPerformed

    private void entrarButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButMouseEntered
        entrarBut.setBackground(Color.green);
    }//GEN-LAST:event_entrarButMouseEntered

    private void entrarButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButMouseExited
        entrarBut.setBackground(Color.red);
    }//GEN-LAST:event_entrarButMouseExited

    private void cadastrarButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButton1MouseEntered
        cadastrarButton1.setBackground(Color.cyan);
    }//GEN-LAST:event_cadastrarButton1MouseEntered

    private void cadastrarButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButton1MouseExited
        cadastrarButton1.setBackground(Color.red);
    }//GEN-LAST:event_cadastrarButton1MouseExited

    private boolean nomeSenhaNotBlank(){
        if(nomeTextField1.getText().equals("") || senhaTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Os espaços de nome e senha não podem estar vazios.");
            return false;
        }
        return true;
    }
    
    private void checarLogin(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pst = c.prepareStatement("select * from cachorro_clientes where nome = ? and senha = ?");
            pst.setString(1, nomeTextField1.getText());
            pst.setString(2, senhaTextField1.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Você tem permissão para entrar no esquema.");
                PaginaInicial pag = new PaginaInicial();
                pag.setUsuario(nomeTextField1.getText());
                pag.criarCarrinhoInicial();
                pag.limparCarrinho();
                this.dispose();
                pag.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você nao tem permissão para entrar no esquema.");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cadastrarButton1;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton entrarBut;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField1;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField senhaTextField1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
