
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tofuto
 */
public class Manutencao extends javax.swing.JFrame {
    private String usuario;

    public String getUsuario() {
        return usuario;
    }

    public void setUser(String u) {
        this.usuario = u;
    }
    
    private void delete(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement ps = c.prepareStatement("delete from cachorro_clientes where nome = ?");
            ps.setString(1, nomeTextField.getText());
            ps.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void add(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement ps = c.prepareStatement("insert into cachorro_clientes(nome, senha,signo,deusa,admin) values (?,?,?,?,?)");
            ps.setString(1, nomeTextField.getText());
            ps.setString(2, senhaTextField.getText());
            ps.setString(3, signoTextField.getText());
            ps.setString(4, deusaTextField.getText());
            ps.setBoolean(5, adminCheckBox.isSelected());
            ps.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void edit(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement ps = c.prepareStatement("update cachorro_clientes set senha = ?, signo = ?, deusa = ? where nome = ?");
            ps.setString(1, senhaTextField.getText());
            ps.setString(2, signoTextField.getText());
            ps.setString(3, deusaTextField.getText());
            ps.setString(4, nomeTextField.getText());
            ps.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * Creates new form Manutencao
     */
    public Manutencao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        background = new javax.swing.JPanel();
        voltarPanel = new javax.swing.JPanel();
        voltarLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        closeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        signoTextField = new javax.swing.JTextField();
        deusaTextField = new javax.swing.JTextField();
        adminCheckBox = new javax.swing.JCheckBox();
        nomeLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        signoLabel = new javax.swing.JLabel();
        deusaLabel = new javax.swing.JLabel();
        delBut = new javax.swing.JButton();
        addBut = new javax.swing.JButton();
        editBut = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 560));
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voltarLabel.setText("          VOLTAR");
        voltarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout voltarPanelLayout = new javax.swing.GroupLayout(voltarPanel);
        voltarPanel.setLayout(voltarPanelLayout);
        voltarPanelLayout.setHorizontalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(voltarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        voltarPanelLayout.setVerticalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(voltarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(voltarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Senha", "Signo", "Deusa", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientesTable);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        background.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));
        background.add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));
        background.add(senhaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));
        background.add(signoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));
        background.add(deusaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, -1));

        adminCheckBox.setText("Admin");
        background.add(adminCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        nomeLabel.setText("Nome");
        background.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        senhaLabel.setText("Senha");
        background.add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        signoLabel.setText("Signo");
        background.add(signoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        deusaLabel.setText("Deusa");
        background.add(deusaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        delBut.setText("Deletar Usuario");
        delBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButActionPerformed(evt);
            }
        });
        background.add(delBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        addBut.setText("Adicionar Usuario");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });
        background.add(addBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        editBut.setText("Editar Usuario");
        editBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButActionPerformed(evt);
            }
        });
        background.add(editBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void atualizarTabela(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement ps = c.prepareStatement("select * from cachorro_clientes");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel dtm = (DefaultTableModel) clientesTable.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Vector v = new Vector();
                for(int i = 1; i<rsmd.getColumnCount(); i++){
                    v.add(rs.getString("nome"));
                    v.add(rs.getString("senha"));
                    v.add(rs.getString("signo"));
                    v.add(rs.getString("deusa"));
                    v.add(rs.getBoolean("admin"));
                }
                dtm.addRow(v);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void voltarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseClicked
        Perfil pf = new Perfil();
        pf.setUser(this.usuario);
        pf.setVisible(true);
        this.dispose();
        pf.checarAdmin();
        pf.atualizarPerfilInfo();
    }//GEN-LAST:event_voltarLabelMouseClicked

    private void voltarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseEntered
        
        Color roberto = new Color(205,201,123);
        voltarPanel.setBackground(roberto);
    }//GEN-LAST:event_voltarLabelMouseEntered

    private void voltarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseExited
        int n1,n2,n3;
        n1 = 242;
        n2 = 242;
        n3 = 242;
        Color cor = new Color(n1,n2,n3);

        voltarPanel.setBackground(cor);
    }//GEN-LAST:event_voltarLabelMouseExited

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void clientesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesTableMouseClicked
        int selectedRowIndex;
        selectedRowIndex = clientesTable.getSelectedRow();
        nomeTextField.setText(clientesTable.getValueAt(selectedRowIndex, 0).toString());
        senhaTextField.setText(clientesTable.getValueAt(selectedRowIndex, 1).toString());
        signoTextField.setText(clientesTable.getValueAt(selectedRowIndex, 2).toString());
        deusaTextField.setText(clientesTable.getValueAt(selectedRowIndex, 3).toString());
        adminCheckBox.setSelected((boolean) clientesTable.getValueAt(selectedRowIndex, 4));
    }//GEN-LAST:event_clientesTableMouseClicked

    private void editButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButActionPerformed
        edit();
        atualizarTabela();
    }//GEN-LAST:event_editButActionPerformed

    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        add();
        atualizarTabela();
    }//GEN-LAST:event_addButActionPerformed

    private void delButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButActionPerformed
        delete();
        atualizarTabela();
    }//GEN-LAST:event_delButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBut;
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JPanel background;
    private javax.swing.JTable clientesTable;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton delBut;
    private javax.swing.JLabel deusaLabel;
    private javax.swing.JTextField deusaTextField;
    private javax.swing.JButton editBut;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JLabel signoLabel;
    private javax.swing.JTextField signoTextField;
    private javax.swing.JLabel voltarLabel;
    private javax.swing.JPanel voltarPanel;
    // End of variables declaration//GEN-END:variables
}
