
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tofuto
 */
public class PaginaInicial extends javax.swing.JFrame {
    private String usuario;
    void setUsuario(String user){
        this.usuario = user;
    }
    
    
    
    /**
     * Creates new form PaginaInicial
     */
    
    public PaginaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        carrinhoPanel.setVisible(false);
        
        
        
    }
    
    
    public void criarCarrinhoInicial(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pst = c.prepareStatement("select * from cachorro_carrinho where nome = ?");
            pst.setString(1, usuario);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
            }else{
                PreparedStatement pst2 = c.prepareStatement("insert into cachorro_carrinho(usuario, nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNsei, quantPior) values (?,?,0,0,0,0,0,0)");
                pst2.setString(1, usuario);
                pst2.setString(2, usuario);
                pst2.execute();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void limparCarrinho(){
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantLGTV = 0, quantOiCadela = 0, quantMedo = 0, quantSMT = 0, quantNsei = 0, quantPior = 0 where nome = ? ");
            pst.setString(1, usuario);
            pst.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        quantCuritiba = new javax.swing.JLabel();
        imgNsei = new javax.swing.JLabel();
        quantSMT = new javax.swing.JLabel();
        quantMedoCuritibaTxt = new javax.swing.JLabel();
        quantPiorqe = new javax.swing.JLabel();
        quantPiorqeTxt = new javax.swing.JLabel();
        smtCar = new javax.swing.JButton();
        compNseisecomento = new javax.swing.JButton();
        contraOiCadela = new javax.swing.JButton();
        compOiCadela = new javax.swing.JButton();
        lgtvCar = new javax.swing.JButton();
        imgOiCadela = new javax.swing.JLabel();
        compSeMata = new javax.swing.JButton();
        contraNseisecomento = new javax.swing.JButton();
        nseiCar = new javax.swing.JButton();
        contraPiorqe = new javax.swing.JButton();
        contraLGTV = new javax.swing.JButton();
        oicadelaCar = new javax.swing.JButton();
        imgSMT = new javax.swing.JLabel();
        imgLGTV = new javax.swing.JLabel();
        contraCuritiba = new javax.swing.JButton();
        quantSMTTxt = new javax.swing.JLabel();
        imgMedoCuritiba = new javax.swing.JLabel();
        quantOiCadela = new javax.swing.JLabel();
        carrinhoBut = new javax.swing.JButton();
        quantLGTV = new javax.swing.JLabel();
        quantNseiTxt = new javax.swing.JLabel();
        curitibaCar = new javax.swing.JButton();
        quantLGTVTxt = new javax.swing.JLabel();
        quantOiCadelaTxt = new javax.swing.JLabel();
        perfilBut = new javax.swing.JButton();
        piorqeCar = new javax.swing.JButton();
        compLGTV = new javax.swing.JButton();
        contraSMT = new javax.swing.JButton();
        quantNseisecomento = new javax.swing.JLabel();
        imgPiorqe = new javax.swing.JLabel();
        compPiorqe = new javax.swing.JButton();
        compCuritiba = new javax.swing.JButton();
        carrinhoPanel = new javax.swing.JPanel();
        finalCompra = new javax.swing.JButton();
        sairCarrinhoPanel = new javax.swing.JPanel();
        sairCarLabel = new javax.swing.JLabel();
        tabelaScrollPane = new javax.swing.JScrollPane();
        carrinhoTable = new javax.swing.JTable();
        imgCachorroCarrinho = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 800));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(950, 800));
        mainPanel.setMinimumSize(new java.awt.Dimension(950, 800));
        mainPanel.setPreferredSize(new java.awt.Dimension(950, 800));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantCuritiba.setText("5200");
        mainPanel.add(quantCuritiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 20));

        imgNsei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSeiSeComento.jpg"))); // NOI18N
        mainPanel.add(imgNsei, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 160));

        quantSMT.setText("5");
        mainPanel.add(quantSMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 20, -1));

        quantMedoCuritibaTxt.setText("Quantidade ele tem medo de curitiba");
        mainPanel.add(quantMedoCuritibaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        quantPiorqe.setText("990");
        mainPanel.add(quantPiorqe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        quantPiorqeTxt.setText("Quantidade pior q e =");
        mainPanel.add(quantPiorqeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        smtCar.setText("Adicionar ao carrinho de compras");
        smtCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtCarActionPerformed(evt);
            }
        });
        mainPanel.add(smtCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        compNseisecomento.setText("Comprar n sei se comento");
        compNseisecomento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compNseisecomentoActionPerformed(evt);
            }
        });
        mainPanel.add(compNseisecomento, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        contraOiCadela.setText("Contrabander OiCadela");
        contraOiCadela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraOiCadelaActionPerformed(evt);
            }
        });
        mainPanel.add(contraOiCadela, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        compOiCadela.setText("Comprar OiCadela");
        compOiCadela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compOiCadelaActionPerformed(evt);
            }
        });
        mainPanel.add(compOiCadela, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lgtvCar.setText("Adicionar ao carrinho de compras");
        lgtvCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgtvCarActionPerformed(evt);
            }
        });
        mainPanel.add(lgtvCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        imgOiCadela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OiCadela.jpg"))); // NOI18N
        mainPanel.add(imgOiCadela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        compSeMata.setText("Comprar se mata");
        compSeMata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compSeMataActionPerformed(evt);
            }
        });
        mainPanel.add(compSeMata, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        contraNseisecomento.setText("Contrabandear n sei se comento");
        contraNseisecomento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraNseisecomentoActionPerformed(evt);
            }
        });
        mainPanel.add(contraNseisecomento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        nseiCar.setText("Adicionar ao carrinho de compras");
        nseiCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nseiCarActionPerformed(evt);
            }
        });
        mainPanel.add(nseiCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        contraPiorqe.setText("Contrabandear Pior q e");
        contraPiorqe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraPiorqeActionPerformed(evt);
            }
        });
        mainPanel.add(contraPiorqe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        contraLGTV.setText("Contrabandear LGTV");
        contraLGTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraLGTVActionPerformed(evt);
            }
        });
        mainPanel.add(contraLGTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        oicadelaCar.setText("Adicionar ao carrinho de compras");
        oicadelaCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oicadelaCarActionPerformed(evt);
            }
        });
        mainPanel.add(oicadelaCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        imgSMT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SeMata.jpg"))); // NOI18N
        mainPanel.add(imgSMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        imgLGTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LGTV.jpg"))); // NOI18N
        mainPanel.add(imgLGTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contraCuritiba.setText("Contrabandear ele tem medo de curitiba");
        contraCuritiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraCuritibaActionPerformed(evt);
            }
        });
        mainPanel.add(contraCuritiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        quantSMTTxt.setText("Quantidade se mata = ");
        mainPanel.add(quantSMTTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        imgMedoCuritiba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedoCuritiba.jpg"))); // NOI18N
        mainPanel.add(imgMedoCuritiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        quantOiCadela.setText("3");
        mainPanel.add(quantOiCadela, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 10, -1));

        carrinhoBut.setText("VER CARRINHO");
        carrinhoBut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.darkGray, java.awt.Color.darkGray));
        carrinhoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrinhoButActionPerformed(evt);
            }
        });
        mainPanel.add(carrinhoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 120, 40));

        quantLGTV.setText("50");
        mainPanel.add(quantLGTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        quantNseiTxt.setText("Quantidade n sei se comento =");
        mainPanel.add(quantNseiTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        curitibaCar.setText("Adicionar ao carrinho de compras");
        curitibaCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curitibaCarActionPerformed(evt);
            }
        });
        mainPanel.add(curitibaCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        quantLGTVTxt.setText("Quantidade LGTV =");
        mainPanel.add(quantLGTVTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        quantOiCadelaTxt.setText("Quantidade Oi Cadela =");
        mainPanel.add(quantOiCadelaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        perfilBut.setText("VER PERFIL");
        perfilBut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.darkGray, java.awt.Color.darkGray));
        perfilBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilButActionPerformed(evt);
            }
        });
        mainPanel.add(perfilBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 120, 40));

        piorqeCar.setText("Adicionar ao carrinho de compras");
        piorqeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piorqeCarActionPerformed(evt);
            }
        });
        mainPanel.add(piorqeCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        compLGTV.setText("Comprar LGTV");
        compLGTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compLGTVActionPerformed(evt);
            }
        });
        mainPanel.add(compLGTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        contraSMT.setText("Contrabandear se mata");
        contraSMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraSMTActionPerformed(evt);
            }
        });
        mainPanel.add(contraSMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        quantNseisecomento.setText("200");
        mainPanel.add(quantNseisecomento, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        imgPiorqe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PiorQE.jpg"))); // NOI18N
        mainPanel.add(imgPiorqe, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        compPiorqe.setText("Comprar pior que e ");
        compPiorqe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compPiorqeActionPerformed(evt);
            }
        });
        mainPanel.add(compPiorqe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        compCuritiba.setText("Comprar ele tem medo de curitiba");
        compCuritiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compCuritibaActionPerformed(evt);
            }
        });
        mainPanel.add(compCuritiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, 800));

        carrinhoPanel.setBackground(new java.awt.Color(255, 255, 255));
        carrinhoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finalCompra.setText("Finalizar Compra");
        finalCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCompraActionPerformed(evt);
            }
        });
        carrinhoPanel.add(finalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        sairCarrinhoPanel.setBackground(new java.awt.Color(255, 255, 204));
        sairCarrinhoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sairCarLabel.setText("       SAIR DO CARRINHO");
        sairCarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairCarLabelMouseClicked(evt);
            }
        });
        sairCarrinhoPanel.add(sairCarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        carrinhoPanel.add(sairCarrinhoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        carrinhoTable.setBackground(new java.awt.Color(204, 255, 204));
        carrinhoTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        carrinhoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "LGTVS", "OiCadelas", "EleTemMedoDeCuritiba", "SeMata", "NSeiSeComento", "Pior que e"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carrinhoTable.setGridColor(new java.awt.Color(204, 204, 255));
        carrinhoTable.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabelaScrollPane.setViewportView(carrinhoTable);

        carrinhoPanel.add(tabelaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 70, 780, 120));

        imgCachorroCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/126510.png"))); // NOI18N
        carrinhoPanel.add(imgCachorroCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        getContentPane().add(carrinhoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, 800));

        topPanel.setBackground(new java.awt.Color(0, 153, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        topPanel.add(closeLabel, java.awt.BorderLayout.LINE_END);

        logoutPanel.setBackground(new java.awt.Color(255, 51, 51));
        logoutPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutLabel.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        logoutLabel.setText("LOGOUT");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        logoutPanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        topPanel.add(logoutPanel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compLGTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compLGTVActionPerformed
        int n = Integer.parseInt(quantLGTV.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Digite um valor valido... Nos nao temos tantos assim...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Nos nao temos cachorros negativos... e vc n pode comprar 0 cachorros agora que clicou em comprar");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            }if(totalComprados == n){
                    JOptionPane.showMessageDialog(null, "QUE ISSO PARCEIRO VOCE COMPROU TODOS LGTV???? eita...");
            }else{
                JOptionPane.showMessageDialog(null, "Voce comprou um LGTV!!! esse olhar dele diz mt sobre voce...");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,?,0,0,0,0,0)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantLGTV.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem lgtv no estoque... o mundo foi dominado?");
        }
    }//GEN-LAST:event_compLGTVActionPerformed
    
    private void contraLGTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraLGTVActionPerformed
        int n = Integer.parseInt(quantLGTV.getText());
        String nome = "LGTV";
        String[] op = {"Fujo!!", "Nao fujo..."};
        JOptionPane.showMessageDialog(null,"A POLICIA ESTA ATRAS DE VOCE POR CONTRABANDEAR UM LGTV?" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "Voce fugiu da policia!!!! agora tem mais um lgtv no estoque te olhando...");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantLGTV.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "A POLICIA VE SEU LGTV E TE JULGA PROFUNDADMENTE!!!... voce foi preso");
            //this.dispose();
        }
    }//GEN-LAST:event_contraLGTVActionPerformed

    private void compOiCadelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compOiCadelaActionPerformed
       
        int n = Integer.parseInt(quantOiCadela.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce deseja comprar?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Digite um valor valido... Nos nao temos tantos assim... ainda mais oi cadelas que sao extremamente escassos..");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce deseja comprar?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Nos nao temos cachorros negativos so o Se mata, mas ainda assim n da pra comprar cachorros com o valor negativo...\nE vc n pode comprar 0 cachorros agora que clicou em comprar");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce deseja comprar?"));
            }if(totalComprados == n){
                    JOptionPane.showMessageDialog(null, "QUE ISSO PARCEIRO VOCE COMPROU TODOS OI CADELA???? A GENTE TINHA POUCOS JA AGORA ELES VAO SEDUZIR TODO MUNDO...");
            }else{
                JOptionPane.showMessageDialog(null, "Voce comprou um Oi Cadela!!! Um cara sedutor, o bairro esta em perigo...");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,0,?,0,0,0,0)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantOiCadela.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem oi cadela no estoque... Cachorro raro e garanhao e assim");
        }
    }//GEN-LAST:event_compOiCadelaActionPerformed

    private void contraOiCadelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraOiCadelaActionPerformed
        int n = Integer.parseInt(quantOiCadela.getText());
        String nome = "Oi Cadela";
        String[] op = {"Fujo!!", "Nao fujo..."};
        JOptionPane.showMessageDialog(null,"A POLICIA ESTA ATRAS DE VOCE POR CONTRABANDEAR UM OI CADELA" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "Voce fugiu da policia!!!! agora tem mais um raro Oi cadela no estoque, talvez assim tenha mais clientes...");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantOiCadela.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "A POLICIA VE SEU OI CADELA E FICA HIPNOTIZADA, voce nao foi preso mas n tem oi cadelas a mais no estoque");
            //this.dispose();
        }
    }//GEN-LAST:event_contraOiCadelaActionPerformed

    private void compCuritibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compCuritibaActionPerformed
        int n = Integer.parseInt(quantCuritiba.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja comprar?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Nos nao temos tantos Ele Tem Medo De Curitiba quanto vc quer comprar... tem que esperar mais alguns fugirem e teleportarem pra ca... ou contrabando ne");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja comprar?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Voce nao pode comprar 0 cachorros se vc ja clicou em comprar ne... E TAMBEM NAO DA PRA COMPRAR CACHORROS NEGATIVOS");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja comprar?"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "MALUCO VOCE TA COMPRANDO TODOS? eu espero muito que voce n more em Curitiba...");
            }
            String[] op = {"Moro em curitiba!", "Nao moro em curitiba!"};
            int j = JOptionPane.showOptionDialog(null,"Voce mora em curitiba?", "Tenso",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
            if(j==0){
                if(totalComprados != n){
                JOptionPane.showMessageDialog(null, "O CACHORRO TELEPORTA E FOGE DE CURITIBA VOCE TA MALUCO??? voce n tem cachorro e a gente tem menos " + totalComprados + " no estoque agora.");
                }else{
                    JOptionPane.showMessageDialog(null, "Porra, voce comprou todos ele tem medo de curitiba e mora em curitiba? TA QUERENDO ME FODER NE?");
                }
            }else{
                JOptionPane.showMessageDialog(null, "O cachorro fica bem feliz com isso!");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,0,0,?,0,0,0)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantCuritiba.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem ele tem medo de curitiba no estoque... Talvez se a gente for pra longe de curitiba venha mais");
        }
    }//GEN-LAST:event_compCuritibaActionPerformed

    private void contraCuritibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraCuritibaActionPerformed
        int n = Integer.parseInt(quantCuritiba.getText());
        String[] op = {"Fujo!!", "Nao fujo..."};
        String nome = "Tenho medo de curitiba";
        JOptionPane.showMessageDialog(null,"A POLICIA ESTA ATRAS DE VOCE POR CONTRABANDEAR UM ELE TEM MEDO DE CURITIBA" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "Voce fugiu da policia!!!! agora tem mais um Ele tem medo de curitiba no estoque!! Tomara que n apareca uma curitiba por aqui, eles fogem");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantCuritiba.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "VOCE OLHA PRO LADO E O ELE TEM MEDO DE CURITIBA SUMIU A POLICIA TE PRENDEU EM CURITIBA!!");
            //this.dispose();
        }

    }//GEN-LAST:event_contraCuritibaActionPerformed

    private void compSeMataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compSeMataActionPerformed
       int n = Integer.parseInt(quantSMT.getText());
       int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce quer comprar??"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "A GENTE NAO TEM TANTOS SE MATA ASSIM... e dificil pegar eles no skate");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce quer comprar??"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "NAO DA PRA COMPRAR CACHORROS NEGATIVOS OU ZERO CACHORROS AGORA QUE VOCE JA CLICOU EM COMPRAR! se bem que um se mata e bem negativo mesmo ");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce quer comprar??"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "MANO VOCE TA COMPRANDO TODOS SE MATA? e muito cachorro andando de skate por ai... tambem meio preocupado com sua saude mental ne, mas escolhas");
            }else{
            JOptionPane.showMessageDialog(null, "Voce comprou um se mata!!! Ele ta no skate... andando por ai...");
            }try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,0,0,0,?,0,0)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantSMT.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem se mata no estoque... devem estar andando de skate por ai");
        }
    }//GEN-LAST:event_compSeMataActionPerformed

    private void contraSMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraSMTActionPerformed
        int n = Integer.parseInt(quantSMT.getText());
        String nome = "Se mata";
        String[] op = {"Fujo!!", "Nao fujo..."};
        JOptionPane.showMessageDialog(null,"A POLICIA ESTA ATRAS DE VOCE POR CONTRABANDEAR UM SE MATA" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "Voce fugiu da policia!!!! agora tem mais um Se Mata no estoque... se ele n fugir de skate ou sei la mandar um cliente se matar");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantSMT.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "ENQUANTO VOCE VAI PRESO VOCE OLHA PRO LADO E O SE MATA TA ANDANDO DE SKATE FAZENDO MANOBRAS");
            //this.dispose();
        }
    }//GEN-LAST:event_contraSMTActionPerformed

    private void compNseisecomentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compNseisecomentoActionPerformed
         int n = Integer.parseInt(quantNseisecomento.getText());
         int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer comprar? Eles n vao comentar..."));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "A GENTE N TEM TANTOS N SEI SE COMENTA NO ESTOQUE ASSIM... \n Ta querendo comprar muitos, ainda que eles n comentam entao e dificil de achar muitos a gente acha de pouquinho em pouquinho so");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer comprar? Eles n vao comentar..."));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Olha, acho que com voce comprando cachorros negativos ou comprando zero cachorros eles vao comentar alguma coisa...\n So nao vai ser coisa boa ne...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer comprar? Eles n vao comentar..."));
            }if(totalComprados == n ){
                JOptionPane.showMessageDialog(null, "CARA VOCE COMPROU TODOS NAO SEI SE COMENTO? ta querendo ver se algum finalmente comenta ne");
            }else{
            JOptionPane.showMessageDialog(null, "Voce comprou um Nao sei se comento!!! Ele ta em duvida se comenta sobre ou nao...");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,0,0,0,0,?,0)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n-totalComprados;
            quantNseisecomento.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem Nao sei se comento! Devem ter comentado ne");
        }
    }//GEN-LAST:event_compNseisecomentoActionPerformed

    private void contraNseisecomentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraNseisecomentoActionPerformed
        int n = Integer.parseInt(quantNseisecomento.getText());
        String nome = "Nao sei se comento";
        String[] op = {"Fujo!!", "Nao fujo..."};
        JOptionPane.showMessageDialog(null,"A POLICIA ESTA ATRAS DE VOCE POR CONTRABANDEAR N SEI SE COMENTO" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "VOCE FUGIU!! Agora tem mais um Nao sei se comento no estoque, o que eles devem achar disso ne");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantNseisecomento.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "VOCE FOI PRESO E O N SEI SE COMENTO COMENTOU!!! ele ta decepcionado.");
            //this.dispose();
        }
    }//GEN-LAST:event_contraNseisecomentoActionPerformed

    private void compPiorqeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compPiorqeActionPerformed
        int n = Integer.parseInt(quantPiorqe.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer comprar?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Pior que a gente ta sem tantos pior que e assim no estoque... pior que vai ter que comprar menos");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer comprar?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Pior que voce nao pode comprar pior que e negativo, nem 0 pior que e...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer comprar?"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "PIOR QUE VOCE COMPROU TODOS PIOR QUE E..... pior que agora n tem nenhum no estoque...");
            }else{
            JOptionPane.showMessageDialog(null, " VOCE COMPROU UM PIOR QUE E!! Pior que e.");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNSei, quantPiorqe) values (?,0,0,0,0,0,?)");
                pst.setString(1, usuario);
                pst.setInt(2, totalComprados);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantPiorqe.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Pior que estamos sem pior que e");
        }
    }//GEN-LAST:event_compPiorqeActionPerformed

    private void contraPiorqeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraPiorqeActionPerformed
        int n = Integer.parseInt(quantPiorqe.getText());
        String[] op = {"Fujo!!", "Nao fujo..."};
        String nome = "Pior que e";
        JOptionPane.showMessageDialog(null,"PIOR QUE A POLICIA TA ATRAS DE VOCE POR CONTRABANDEAR UM PIOR QUE E" );
        int j = JOptionPane.showOptionDialog(null,"Voce foge?", "Policia",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
        if(j==0){
            JOptionPane.showMessageDialog(null, "VOCE FUGIU!! Pior que agora tem mais um pior que e no stock");
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("insert into cachorro_contrabandos(nome, cachorroContrabandeado) values (?,?)");
                pst.setString(1, usuario);
                pst.setString(2, nome);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n++;
            quantPiorqe.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Pior que voce foi preso e o pior que e foi embora.");
            //this.dispose();
        }
    }//GEN-LAST:event_contraPiorqeActionPerformed

    private void carrinhoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrinhoButActionPerformed
        carrinhoPanel.setVisible(true);
        mainPanel.setVisible(false);
        atualizarCarrinhoDeCompras();
        
    }//GEN-LAST:event_carrinhoButActionPerformed
    
    private void lgtvCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgtvCarActionPerformed
        int n = Integer.parseInt(quantLGTV.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Digite um valor valido... Nos nao temos tantos assim...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Nos nao temos cachorros negativos... e vc n pode comprar 0 cachorros agora que clicou em comprar");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos LGTV voce deseja comprar?"));
            }if(totalComprados == n){
                    JOptionPane.showMessageDialog(null, "QUE ISSO PARCEIRO VOCE BOTOU TODOS LGTV NO CARRINHO???? eita... nao vai caber.");
            }else{
                JOptionPane.showMessageDialog(null, "Seu LGTV foi para o carrinho de compras!! \nEle ta te olhando daquele jeito...");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantLGTV = quantLGTV + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantLGTV.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem lgtv no estoque... o mundo foi dominado?");
        }
    }//GEN-LAST:event_lgtvCarActionPerformed

    private void perfilButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilButActionPerformed
        Perfil pf = new Perfil();
        pf.setUser(this.usuario);
        pf.setVisible(true);
        this.dispose();
        pf.checarAdmin();
        pf.atualizarPerfilInfo();
        
    }//GEN-LAST:event_perfilButActionPerformed
    private void atualizarCarrinhoDeCompras(){
        try{
        DefaultTableModel model = (DefaultTableModel)carrinhoTable.getModel();
        Connection c = DBCConnection.getConnection();
        PreparedStatement pst = c.prepareStatement("select * from cachorro_carrinho where usuario = ?");
        pst.setString(1, usuario);
        ResultSet rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        model.setRowCount(0);
        int n = rsmd.getColumnCount();
        while(rs.next()){
        Vector v = new Vector();
        for(int j = 1; j<=n; j++){
            v.add(rs.getString("nome"));
            v.add(rs.getInt("quantLGTV"));
            v.add(rs.getInt("quantOiCadela"));
            v.add(rs.getInt("quantMedo"));
            v.add(rs.getInt("quantSMT"));
            v.add(rs.getInt("quantNsei"));
            v.add(rs.getInt("quantPior"));
        }
        model.addRow(v);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
        
    private void sairCarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairCarLabelMouseClicked
        carrinhoPanel.setVisible(false);
        mainPanel.setVisible(true);
    }//GEN-LAST:event_sairCarLabelMouseClicked

    private void finalCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCompraActionPerformed
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pst = c.prepareStatement("select * from cachorro_carrinho where nome = ?");
            pst.setString(1, usuario);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
            PreparedStatement pst2 = c.prepareStatement("insert into cachorro_compras(nome, quantLGTV, quantOiCadela, quantMedo, quantSMT, quantNsei, quantPiorqe) values (?,?,?,?,?,?,?)");
            pst2.setString(1, rs.getString("nome"));
            pst2.setInt(2, rs.getInt("quantLGTV"));
            pst2.setInt(3, rs.getInt("quantOiCadela"));
            pst2.setInt(4, rs.getInt("quantMedo"));
            pst2.setInt(5, rs.getInt("quantSMT"));
            pst2.setInt(6, rs.getInt("quantNsei"));
            pst2.setInt(7, rs.getInt("quantPior"));
            pst2.execute();
            JOptionPane.showMessageDialog(null, "Compra concluida!");
            limparCarrinho();
            atualizarCarrinhoDeCompras();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_finalCompraActionPerformed

    private void oicadelaCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oicadelaCarActionPerformed
        
        int n = Integer.parseInt(quantOiCadela.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce quer botar no carrinho?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Digite um valor valido... Nos nao temos tantos assim... ainda mais oi cadelas que sao extremamente escassos..");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce quer botar no carrinho?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Nos nao temos cachorros negativos  so o se mata mas ele tbm n da pra colocar negativo no carrinho... \nE vc n pode botar 0 cachorros no carrinho agora que clicou em adicionar");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Oi Cadela voce quer botar no carrinho?"));
            }if(totalComprados == n){
                    JOptionPane.showMessageDialog(null, "QUE ISSO PARCEIRO VOCE BOTOU TODOS OI CADELA NO CARRINHO???? \nA GENTE TINHA POUCOS JA, AGORA ELES VAO SEDUZIR TODO MUNDO... \npelo menos como tinha pouco cabe no carrinho tranquilo");
            }else{
                JOptionPane.showMessageDialog(null, "Voce colocou um Oi Cadela no carrinho!!! Um cara sedutor, o bairro esta em perigo...");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantOiCadela = quantOiCadela + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantOiCadela.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem oi cadela no estoque... Cachorro raro e garanhao e assim");
        }
                                                
    }//GEN-LAST:event_oicadelaCarActionPerformed

    private void curitibaCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curitibaCarActionPerformed
            int n = Integer.parseInt(quantCuritiba.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja colocar no carrinho?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Nos nao temos tantos Ele Tem Medo De Curitiba quanto vc quer botar no carrinho... tem que esperar mais alguns fugirem e teleportarem pra ca... ou contrabando ne");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja colocar no carrinho?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Voce nao pode colocar 0 cachorros no carrinho se vc ja clicou em adicionar ao carrinho ne... \nE TAMBEM NAO DA PRA ADICIONAR CACHORROS NEGATIVOS");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Ele Tem Medo De Curitiba voce deseja colocar no carrinho?"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "MALUCO VOCE TA COLOCANDO TODOS NO CARRINHO? eu espero muito que voce n more em Curitiba...");
            }
            String[] op = {"Moro em curitiba!", "Nao moro em curitiba!"};
            int j = JOptionPane.showOptionDialog(null,"Voce mora em curitiba?", "Tenso",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, op, op[0]);
            if(j==0){
                if(totalComprados != n){
                JOptionPane.showMessageDialog(null, "O CACHORRO TELEPORTA E FOGE DE CURITIBA VOCE TA MALUCO??? voce n tem cachorro e a gente tem menos " + totalComprados + " no estoque agora.");
                }else{
                    JOptionPane.showMessageDialog(null, "Porra, voce botou todos ele tem medo de curitiba no carrinho e mora em curitiba? TA QUERENDO ME FODER NE? \n Ai mimimi eu so botei eles no carrinho nao tinha como eles saberem que eu moro em curitiba mimimi\n Eles sentem.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "O cachorro fica bem feliz com isso!");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantMedo = quantMedo + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantCuritiba.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem ele tem medo de curitiba no estoque... Talvez se a gente for pra longe de curitiba venha mais");
        }
    }//GEN-LAST:event_curitibaCarActionPerformed

    private void smtCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtCarActionPerformed
             int n = Integer.parseInt(quantSMT.getText());
       int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce colocar no carrinho"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "A GENTE NAO TEM TANTOS SE MATA ASSIM... e dificil pegar eles no skate");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce quer colocar no carrinho"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "NAO DA PRA COLOCAR CACHORROS NEGATIVOS OU ZERO CACHORROS NO CARRINHO AGORA QUE VOCE JA CLICOU EM ADICIONAR!\n se bem que um se mata e bem negativo mesmo ");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos Se Mata voce quer colocar no carrinho??"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "MANO VOCE TA COLOCANDO TODOS SE MATA NO CARRINHO? \ne mais facil deixar eles acompanhando no lado do carrinho de skate... \ntambem meio preocupado com sua saude mental ne, mas escolhas");
            }else{
            JOptionPane.showMessageDialog(null, "Voce colocou um se mata no carrinho!!! Ele ta no skate... \nMelhor deixar fora do carrinho e falar pra ele ir com voce acompanhando...");
            }try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantSMT = quantSMT + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantSMT.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem se mata no estoque... devem estar andando de skate por ai");
        }
    }//GEN-LAST:event_smtCarActionPerformed

    private void nseiCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nseiCarActionPerformed
            int n = Integer.parseInt(quantNseisecomento.getText());
         int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer colocar no carrinho? Eles n vao comentar..."));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "A GENTE N TEM TANTOS N SEI SE COMENTA NO ESTOQUE ASSIM... \n Ta querendo botar muitos no carrinho, ainda que eles n comentam entao e dificil de achar muitos a gente acha de pouquinho em pouquinho so");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer colocar no carrinho? Eles n vao comentar..."));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Olha, acho que com voce comprando cachorros negativos ou comprando zero cachorros eles vao comentar alguma coisa...\n So nao vai ser coisa boa ne...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Quantos n sei se comento voce quer colocar no carrinho? Eles n vao comentar..."));
            }if(totalComprados == n ){
                JOptionPane.showMessageDialog(null, "CARA VOCE BOTOU TODOS NAO SEI SE COMENTO NO CARRINHO? ta querendo ver se algum finalmente comenta ne\n Se bem que se tiver muitos cachorros no carrinho talvez eles façam comentários meio negativos ou coisa do tipo");
            }else{
            JOptionPane.showMessageDialog(null, "Voce botou um Nao sei se comento no carrinho!!! \nEle ta em duvida se comenta sobre ou nao... \nO carrinho e bem pequeno mesmo ou e alguma coisa com voce ne");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantNsei = quantNsei + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n-totalComprados;
            quantNseisecomento.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Estamos sem Nao sei se comento! Devem ter comentado ne");
        }
    }//GEN-LAST:event_nseiCarActionPerformed

    private void piorqeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piorqeCarActionPerformed
        int n = Integer.parseInt(quantPiorqe.getText());
        int totalComprados;
        if(n>0){
            totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer colocar no carrinho?"));
            while(totalComprados>n){
                JOptionPane.showMessageDialog(null, "Pior que a gente ta sem tantos pior que e assim no estoque... pior que vai ter que botar menos no carrinho");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer colocar no carrinho?"));
            }while(totalComprados<=0){
                JOptionPane.showMessageDialog(null, "Pior que voce nao pode adicionar pior que e negativo no carrinho, nem 0 pior que e...");
                totalComprados = Integer.parseInt(JOptionPane.showInputDialog("Pior que quantos pior que e voce quer colocar no carrinho?"));
            }if(totalComprados==n){
                JOptionPane.showMessageDialog(null, "PIOR QUE VOCE COLOCOU TODOS PIOR QUE E NO CARRINHO..... \npior que agora n tem nenhum no estoque... e pior que esse carrinho deve ta apertado...");
            }else{
            JOptionPane.showMessageDialog(null, "VOCE BOTOU UM PIOR QUE E NO CARRINHO!! Pior que e.");
            }
            try{
                Connection c = DBCConnection.getConnection();
                PreparedStatement pst = c.prepareStatement("update cachorro_carrinho set quantPior = quantPior + ? where usuario = ?");
                pst.setInt(1, totalComprados);
                pst.setString(2, usuario);
                pst.execute();
            }catch(Exception e){
                e.printStackTrace();
            }
            n = n - totalComprados;
            quantPiorqe.setText(Integer.toString(n));
        }else{
            JOptionPane.showMessageDialog(null, "Pior que estamos sem pior que e");
        }
    }//GEN-LAST:event_piorqeCarActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carrinhoBut;
    private javax.swing.JPanel carrinhoPanel;
    private javax.swing.JTable carrinhoTable;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton compCuritiba;
    private javax.swing.JButton compLGTV;
    private javax.swing.JButton compNseisecomento;
    private javax.swing.JButton compOiCadela;
    private javax.swing.JButton compPiorqe;
    private javax.swing.JButton compSeMata;
    private javax.swing.JButton contraCuritiba;
    private javax.swing.JButton contraLGTV;
    private javax.swing.JButton contraNseisecomento;
    private javax.swing.JButton contraOiCadela;
    private javax.swing.JButton contraPiorqe;
    private javax.swing.JButton contraSMT;
    private javax.swing.JButton curitibaCar;
    private javax.swing.JButton finalCompra;
    private javax.swing.JLabel imgCachorroCarrinho;
    private javax.swing.JLabel imgLGTV;
    private javax.swing.JLabel imgMedoCuritiba;
    private javax.swing.JLabel imgNsei;
    private javax.swing.JLabel imgOiCadela;
    private javax.swing.JLabel imgPiorqe;
    private javax.swing.JLabel imgSMT;
    private javax.swing.JButton lgtvCar;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nseiCar;
    private javax.swing.JButton oicadelaCar;
    private javax.swing.JButton perfilBut;
    private javax.swing.JButton piorqeCar;
    private javax.swing.JLabel quantCuritiba;
    private javax.swing.JLabel quantLGTV;
    private javax.swing.JLabel quantLGTVTxt;
    private javax.swing.JLabel quantMedoCuritibaTxt;
    private javax.swing.JLabel quantNseiTxt;
    private javax.swing.JLabel quantNseisecomento;
    private javax.swing.JLabel quantOiCadela;
    private javax.swing.JLabel quantOiCadelaTxt;
    private javax.swing.JLabel quantPiorqe;
    private javax.swing.JLabel quantPiorqeTxt;
    private javax.swing.JLabel quantSMT;
    private javax.swing.JLabel quantSMTTxt;
    private javax.swing.JLabel sairCarLabel;
    private javax.swing.JPanel sairCarrinhoPanel;
    private javax.swing.JButton smtCar;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
