
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tofuto
 */
public class SACAdmin extends javax.swing.JFrame {

    private String usuario;
    void setUser(String u){
        this.usuario = u;
    }
    public String getUser(){
        return this.usuario;
    }
    public SACAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        tabelaScrollPane = new javax.swing.JScrollPane();
        feedTable = new javax.swing.JTable();
        voltarPanel = new javax.swing.JPanel();
        voltarLabel = new javax.swing.JLabel();
        usuarioPanel = new javax.swing.JPanel();
        userLabelpan = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        feedBackTextAreaScrollPane = new javax.swing.JScrollPane();
        feedBackTextField = new javax.swing.JTextArea();
        feedLabel = new javax.swing.JLabel();
        respLabel = new javax.swing.JLabel();
        respTextAreaScrollPane = new javax.swing.JScrollPane();
        respostaTextField = new javax.swing.JTextArea();
        responderBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        background.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        feedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "FeedBack", "Resposta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedTableMouseClicked(evt);
            }
        });
        tabelaScrollPane.setViewportView(feedTable);

        background.add(tabelaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 470, -1));

        voltarPanel.setBackground(new java.awt.Color(255, 0, 0));
        voltarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarLabel.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        voltarLabel.setText("     Voltar");
        voltarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarLabelMouseClicked(evt);
            }
        });
        voltarPanel.add(voltarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        background.add(voltarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        javax.swing.GroupLayout usuarioPanelLayout = new javax.swing.GroupLayout(usuarioPanel);
        usuarioPanel.setLayout(usuarioPanelLayout);
        usuarioPanelLayout.setHorizontalGroup(
            usuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabelpan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        usuarioPanelLayout.setVerticalGroup(
            usuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabelpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        background.add(usuarioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 30));

        userLabel.setText("Usuario:");
        background.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        background.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, -1));

        idLabel.setText("ID:");
        background.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        feedBackTextField.setEditable(false);
        feedBackTextField.setColumns(20);
        feedBackTextField.setRows(5);
        feedBackTextAreaScrollPane.setViewportView(feedBackTextField);

        background.add(feedBackTextAreaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 290, 140));

        feedLabel.setText("FeedBack");
        background.add(feedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        respLabel.setText("Resposta");
        background.add(respLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        respostaTextField.setColumns(20);
        respostaTextField.setRows(5);
        respTextAreaScrollPane.setViewportView(respostaTextField);

        background.add(respTextAreaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 270, 120));

        responderBut.setText("Responder");
        responderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderButActionPerformed(evt);
            }
        });
        background.add(responderBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_voltarLabelMouseClicked

    private void feedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)feedTable.getModel();
        int selectedRowIndex = feedTable.getSelectedRow();
        
        userLabelpan.setText(model.getValueAt(selectedRowIndex, 1).toString());
        idTextField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        feedBackTextField.setText(model.getValueAt(selectedRowIndex, 2).toString());
        if(model.getValueAt(selectedRowIndex, 3)== null){
            respostaTextField.setText("");
            
        }else{
        respostaTextField.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
        }
    }//GEN-LAST:event_feedTableMouseClicked

    private void responderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderButActionPerformed
        try{
            Connection con = DBCConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("Update cachorro_feedback set resposta = ? where id = ?");
            pst.setString(1, respostaTextField.getText());
            int n = Integer.parseInt(idTextField.getText());
            pst.setInt(2, n);
            pst.execute();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_responderButActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked
    public void atualizarTabelaFeedbacks(){
                try{
        Connection con = DBCConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("select * from cachorro_feedback");
        ResultSet rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int n = rsmd.getColumnCount();
        DefaultTableModel dtm = (DefaultTableModel) feedTable.getModel();
        dtm.setRowCount(0);
        while(rs.next()){
            Vector v = new Vector();
            for(int i = 1; i<=n;i++ ){
                v.add(rs.getInt("id"));
                v.add(rs.getString("usuario"));
                v.add(rs.getString("feedback"));
                v.add(rs.getString("resposta"));
            }
            dtm.addRow(v);
        }
        
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SACAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SACAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SACAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SACAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SACAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JScrollPane feedBackTextAreaScrollPane;
    private javax.swing.JTextArea feedBackTextField;
    private javax.swing.JLabel feedLabel;
    private javax.swing.JTable feedTable;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel respLabel;
    private javax.swing.JScrollPane respTextAreaScrollPane;
    private javax.swing.JButton responderBut;
    private javax.swing.JTextArea respostaTextField;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabelpan;
    private javax.swing.JPanel usuarioPanel;
    private javax.swing.JLabel voltarLabel;
    private javax.swing.JPanel voltarPanel;
    // End of variables declaration//GEN-END:variables
}
