/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tofuto
 */
public class SACCliente extends javax.swing.JFrame {
    private String usuario;
    void setUser(String u){
        this.usuario = u;
    }
    public String getUser(){
        return this.usuario;
    }
    /**
     * Creates new form SACCliente
     */
    public SACCliente() {
        initComponents();
        verRespostas.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        voltarPanel = new javax.swing.JPanel();
        voltarLabel = new javax.swing.JLabel();
        verFeedback = new javax.swing.JButton();
        darFeedback = new javax.swing.JButton();
        olaLabel = new javax.swing.JLabel();
        feedbackTextAreaScrollPane = new javax.swing.JScrollPane();
        feedTextArea = new javax.swing.JTextArea();
        verRespostas = new javax.swing.JPanel();
        feedBacksScrollPane = new javax.swing.JScrollPane();
        feedTable = new javax.swing.JTable();
        voltarPanel1 = new javax.swing.JPanel();
        voltarLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 550));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        closeLabel.setText(" X");
        closeLabel.setMaximumSize(new java.awt.Dimension(30, 33));
        closeLabel.setMinimumSize(new java.awt.Dimension(30, 33));
        closeLabel.setPreferredSize(new java.awt.Dimension(30, 33));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 30));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(530, 383));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarPanel.setBackground(new java.awt.Color(255, 0, 0));
        voltarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarLabel.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        voltarLabel.setText("     Voltar");
        voltarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarLabelMouseClicked(evt);
            }
        });
        voltarPanel.add(voltarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        mainPanel.add(voltarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        verFeedback.setText("Ver respostas de feedbacks passados");
        verFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFeedbackActionPerformed(evt);
            }
        });
        mainPanel.add(verFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        darFeedback.setText("Dar feedback");
        darFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darFeedbackActionPerformed(evt);
            }
        });
        mainPanel.add(darFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 110, -1));

        olaLabel.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        olaLabel.setText("De seu feedback!");
        mainPanel.add(olaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        feedTextArea.setColumns(20);
        feedTextArea.setRows(5);
        feedbackTextAreaScrollPane.setViewportView(feedTextArea);

        mainPanel.add(feedbackTextAreaScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 480, 200));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 550));

        verRespostas.setBackground(new java.awt.Color(255, 255, 255));
        setVisible(false);
        verRespostas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FeedBack", "Resposta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedTableMouseClicked(evt);
            }
        });
        feedBacksScrollPane.setViewportView(feedTable);

        verRespostas.add(feedBacksScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 310));

        voltarPanel1.setBackground(new java.awt.Color(255, 0, 0));
        voltarPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        voltarLabel1.setText("     Voltar");
        voltarLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarLabel1MouseClicked(evt);
            }
        });
        voltarPanel1.add(voltarLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        verRespostas.add(voltarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        getContentPane().add(verRespostas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darFeedbackActionPerformed
        while(feedTextArea.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Não é possível mandar um feedback vazio... \n O não sei se comento pensa em comentar...");
        }
        try{
            Connection c = DBCConnection.getConnection();
            PreparedStatement pst = c.prepareStatement("insert into cachorro_feedback(feedback, usuario) values (?,?)");
            pst.setString(2, getUser());
            pst.setString(1, feedTextArea.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Feedback registrado!");
        }catch(Exception e){
         e.printStackTrace();
        }
        
        this.dispose();
    }//GEN-LAST:event_darFeedbackActionPerformed

    private void voltarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_voltarLabelMouseClicked

    private void verFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFeedbackActionPerformed
        verRespostas.setVisible(true);
        mainPanel.setVisible(false);
        atualizarTabelaFeedbacks();
    }//GEN-LAST:event_verFeedbackActionPerformed

    private void voltarLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarLabel1MouseClicked
        verRespostas.setVisible(false);
        mainPanel.setVisible(true);
    }//GEN-LAST:event_voltarLabel1MouseClicked

    private void feedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)feedTable.getModel();
        int selectedRowIndex = feedTable.getSelectedRow();
        JOptionPane.showMessageDialog(null, model.getValueAt(selectedRowIndex, 1).toString());
        
    }//GEN-LAST:event_feedTableMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    public void atualizarTabelaFeedbacks(){
                try{
        Connection con = DBCConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("select * from cachorro_feedback where usuario = ?");
        pst.setString(1, usuario);
        ResultSet rs = pst.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int n = rsmd.getColumnCount();
        DefaultTableModel dtm = (DefaultTableModel) feedTable.getModel();
        dtm.setRowCount(0);
        while(rs.next()){
            Vector v = new Vector();
            for(int i = 1; i<=n;i++ ){
                v.add(rs.getString("feedback"));
                v.add(rs.getString("resposta"));
            }
            dtm.addRow(v);
        }
        
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SACCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SACCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SACCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SACCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SACCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton darFeedback;
    private javax.swing.JScrollPane feedBacksScrollPane;
    private javax.swing.JTable feedTable;
    private javax.swing.JTextArea feedTextArea;
    private javax.swing.JScrollPane feedbackTextAreaScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel olaLabel;
    private javax.swing.JButton verFeedback;
    private javax.swing.JPanel verRespostas;
    private javax.swing.JLabel voltarLabel;
    private javax.swing.JLabel voltarLabel1;
    private javax.swing.JPanel voltarPanel;
    private javax.swing.JPanel voltarPanel1;
    // End of variables declaration//GEN-END:variables
}
